//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class All_procss : DbContext
    {
        public All_procss()
            : base("name=All_procss")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Acc_Profile_Result> Acc_Profile(string u)
        {
            var uParameter = u != null ?
                new ObjectParameter("u", u) :
                new ObjectParameter("u", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Acc_Profile_Result>("Acc_Profile", uParameter);
        }
    
        public virtual ObjectResult<AccessRolesSp_Result> AccessRolesSp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AccessRolesSp_Result>("AccessRolesSp");
        }
    
        public virtual int AddPhone(string phone, string email, string user)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddPhone", phoneParameter, emailParameter, userParameter);
        }
    
        public virtual int Checkin_Checkout(string username, string type)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Checkin_Checkout", usernameParameter, typeParameter);
        }
    
        public virtual int Delete_File(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_File", idParameter);
        }
    
        public virtual int Delete_User(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_User", usernameParameter);
        }
    
        public virtual ObjectResult<string> GetData(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetData", idParameter);
        }
    
        public virtual ObjectResult<GetEmp_Result> GetEmp(string staffing)
        {
            var staffingParameter = staffing != null ?
                new ObjectParameter("Staffing", staffing) :
                new ObjectParameter("Staffing", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmp_Result>("GetEmp", staffingParameter);
        }
    
        public virtual ObjectResult<GetEmpUsername_Result> GetEmpUsername(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmpUsername_Result>("GetEmpUsername", idParameter);
        }
    
        public virtual ObjectResult<Gettimesheet_Result> Gettimesheet(string employees, string from_Date, string end_Date)
        {
            var employeesParameter = employees != null ?
                new ObjectParameter("Employees", employees) :
                new ObjectParameter("Employees", typeof(string));
    
            var from_DateParameter = from_Date != null ?
                new ObjectParameter("From_Date", from_Date) :
                new ObjectParameter("From_Date", typeof(string));
    
            var end_DateParameter = end_Date != null ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Gettimesheet_Result>("Gettimesheet", employeesParameter, from_DateParameter, end_DateParameter);
        }
    
        public virtual ObjectResult<Gettimesheet2_Result> Gettimesheet2(string employees)
        {
            var employeesParameter = employees != null ?
                new ObjectParameter("Employees", employees) :
                new ObjectParameter("Employees", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Gettimesheet2_Result>("Gettimesheet2", employeesParameter);
        }
    
        public virtual ObjectResult<PushEmp_Result> PushEmp(string username, string email, string role)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PushEmp_Result>("PushEmp", usernameParameter, emailParameter, roleParameter);
        }
    
        public virtual int Role_Set(Nullable<int> id, string status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Role_Set", idParameter, statusParameter);
        }
    
        public virtual int SetRole(string status, string id, string role)
        {
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SetRole", statusParameter, idParameter, roleParameter);
        }
    
        public virtual ObjectResult<string> sp_departments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_departments");
        }
    
        public virtual int sp_emp_update(Nullable<int> total_leaves)
        {
            var total_leavesParameter = total_leaves.HasValue ?
                new ObjectParameter("Total_leaves", total_leaves) :
                new ObjectParameter("Total_leaves", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_emp_update", total_leavesParameter);
        }
    
        public virtual ObjectResult<Sp_Employee_Result> Sp_Employee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Employee_Result>("Sp_Employee");
        }
    
        public virtual int sp_employee_prog(string staff)
        {
            var staffParameter = staff != null ?
                new ObjectParameter("staff", staff) :
                new ObjectParameter("staff", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_employee_prog", staffParameter);
        }
    
        public virtual ObjectResult<sp_expenses_Result> sp_expenses()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_expenses_Result>("sp_expenses");
        }
    
        public virtual ObjectResult<sp_expenses_report_Result> sp_expenses_report(string startDate, string endDate, string status)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_expenses_report_Result>("sp_expenses_report", startDateParameter, endDateParameter, statusParameter);
        }
    
        public virtual ObjectResult<string> sp_getDrpt(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_getDrpt", userParameter);
        }
    
        public virtual ObjectResult<string> sp_getHodEmail(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_getHodEmail", userParameter);
        }
    
        public virtual int sp_GetRecovery(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetRecovery", idParameter);
        }
    
        public virtual ObjectResult<sp_GetRoles_Result> sp_GetRoles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRoles_Result>("sp_GetRoles");
        }
    
        public virtual ObjectResult<sp_invoices_Result> sp_invoices()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_invoices_Result>("sp_invoices");
        }
    
        public virtual ObjectResult<sp_invoices_report_Result> sp_invoices_report(string startDate, string endDate, string status)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_invoices_report_Result>("sp_invoices_report", startDateParameter, endDateParameter, statusParameter);
        }
    
        public virtual ObjectResult<sp_timesheet_report_Result> sp_timesheet_report(string startDate, string endDate, string status)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_timesheet_report_Result>("sp_timesheet_report", startDateParameter, endDateParameter, statusParameter);
        }
    
        
    
        public virtual int sp_track_leave(Nullable<int> tT_Leaves, Nullable<int> request_days, string user, Nullable<int> id, string approver_Remarks, string approver)
        {
            var tT_LeavesParameter = tT_Leaves.HasValue ?
                new ObjectParameter("TT_Leaves", tT_Leaves) :
                new ObjectParameter("TT_Leaves", typeof(int));
    
            var request_daysParameter = request_days.HasValue ?
                new ObjectParameter("Request_days", request_days) :
                new ObjectParameter("Request_days", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var approver_RemarksParameter = approver_Remarks != null ?
                new ObjectParameter("Approver_Remarks", approver_Remarks) :
                new ObjectParameter("Approver_Remarks", typeof(string));
    
            var approverParameter = approver != null ?
                new ObjectParameter("Approver", approver) :
                new ObjectParameter("Approver", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_track_leave", tT_LeavesParameter, request_daysParameter, userParameter, idParameter, approver_RemarksParameter, approverParameter);
        }
    }
}
