//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string SSRSReportsUrl { get; set; }
        public string Business_mail { get; set; }
    }
}
