//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sp_dash : DbContext
    {
        public sp_dash()
            : base("name=sp_dash")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Dash_1_Result> Dash_1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Dash_1_Result>("Dash_1");
        }
    
        public virtual ObjectResult<Dash_2_Result> Dash_2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Dash_2_Result>("Dash_2");
        }
    
        public virtual ObjectResult<Dash_3_Result> Dash_3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Dash_3_Result>("Dash_3");
        }
    }
}
