//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Config
    {
        public int id { get; set; }
        public Nullable<int> Total_leaves_per_year { get; set; }
        public Nullable<int> Leave_pre_days { get; set; }
        public Nullable<int> Advance_pay_limit { get; set; }
    }
}
