//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GetTtEmp2 : DbContext
    {
        public GetTtEmp2()
            : base("name=GetTtEmp2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Gettimesheet_Result> Gettimesheet(string employees, string from_Date, string end_Date)
        {
            var employeesParameter = employees != null ?
                new ObjectParameter("Employees", employees) :
                new ObjectParameter("Employees", typeof(string));
    
            var from_DateParameter = from_Date != null ?
                new ObjectParameter("From_Date", from_Date) :
                new ObjectParameter("From_Date", typeof(string));
    
            var end_DateParameter = end_Date != null ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Gettimesheet_Result>("Gettimesheet", employeesParameter, from_DateParameter, end_DateParameter);
        }
    }
}
