//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interviewlist
    {
        public int id { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Job_Name { get; set; }
        public string Sector { get; set; }
        public string Type { get; set; }
        public string Posted_by { get; set; }
        public string Applicant { get; set; }
        public string Location { get; set; }
        public string Phone { get; set; }
    }
}
