//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leaves_Days_track
    {
        public int id { get; set; }
        public Nullable<int> Total_leaves_per_year { get; set; }
        public Nullable<int> Requested_leaves { get; set; }
        public Nullable<int> Remaining_leaves { get; set; }
        public string Username { get; set; }
    }
}
