//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leaves_logs
    {
        public int id { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Approver { get; set; }
        public string Approver_status { get; set; }
        public string Approver_remarks { get; set; }
        public Nullable<int> leave_id { get; set; }
    }
}
