//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HREntities : DbContext
    {
        public HREntities()
            : base("name=HREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Acc_Profile_Result> Acc_Profile(string u)
        {
            var uParameter = u != null ?
                new ObjectParameter("u", u) :
                new ObjectParameter("u", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Acc_Profile_Result>("Acc_Profile", uParameter);
        }
    
        public virtual ObjectResult<AccessRolesSp_Result> AccessRolesSp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AccessRolesSp_Result>("AccessRolesSp");
        }
    
        public virtual int AddPhone(string phone, string email, string user)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddPhone", phoneParameter, emailParameter, userParameter);
        }
    
        public virtual int Delete_File(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_File", idParameter);
        }
    
        public virtual int Delete_User(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_User", usernameParameter);
        }
    
        public virtual ObjectResult<Em_Agency_Result> Em_Agency(string employee)
        {
            var employeeParameter = employee != null ?
                new ObjectParameter("employee", employee) :
                new ObjectParameter("employee", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Em_Agency_Result>("Em_Agency", employeeParameter);
        }
    
        public virtual ObjectResult<string> GetData(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetData", idParameter);
        }
    
        public virtual ObjectResult<GetEmp_Result> GetEmp(string staffing)
        {
            var staffingParameter = staffing != null ?
                new ObjectParameter("Staffing", staffing) :
                new ObjectParameter("Staffing", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmp_Result>("GetEmp", staffingParameter);
        }
    
        public virtual ObjectResult<GetEmpUsername_Result> GetEmpUsername(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmpUsername_Result>("GetEmpUsername", idParameter);
        }
    
        public virtual int GetShifts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetShifts");
        }
    
        public virtual ObjectResult<PushEmp_Result> PushEmp(string username, string email, string role)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PushEmp_Result>("PushEmp", usernameParameter, emailParameter, roleParameter);
        }
    
        public virtual int Role_Set(Nullable<int> id, string status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Role_Set", idParameter, statusParameter);
        }
    
        public virtual ObjectResult<RoleGrant_Result> RoleGrant()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RoleGrant_Result>("RoleGrant");
        }
    
        public virtual int RolesAdd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RolesAdd");
        }
    
        public virtual ObjectResult<rolesL_Result> rolesL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rolesL_Result>("rolesL");
        }
    
        public virtual int SetRole(string username, string role)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SetRole", usernameParameter, roleParameter);
        }
    
        public virtual ObjectResult<string> sp_departments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_departments");
        }
    
        public virtual ObjectResult<Sp_Employee_Result> Sp_Employee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Employee_Result>("Sp_Employee");
        }
    
        public virtual ObjectResult<sp_expenses_Result> sp_expenses()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_expenses_Result>("sp_expenses");
        }
    
        public virtual ObjectResult<sp_expenses_report_Result> sp_expenses_report(string startDate, string endDate, string status)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_expenses_report_Result>("sp_expenses_report", startDateParameter, endDateParameter, statusParameter);
        }
    
        public virtual ObjectResult<sp_invoices_Result> sp_invoices()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_invoices_Result>("sp_invoices");
        }
    
        public virtual ObjectResult<sp_invoices_report_Result> sp_invoices_report(string startDate, string endDate, string status)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_invoices_report_Result>("sp_invoices_report", startDateParameter, endDateParameter, statusParameter);
        }
    
        public virtual int sp_markcancelled_expense(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_markcancelled_expense", idParameter);
        }
    
        public virtual int sp_markcancelled_Invoice(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_markcancelled_Invoice", idParameter);
        }
    
        public virtual int sp_markleave_approved(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_markleave_approved", idParameter);
        }
    
        public virtual int sp_markleave_denied(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_markleave_denied", idParameter);
        }
    
        public virtual int sp_markpaid_Invoice(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_markpaid_Invoice", idParameter);
        }
    
        public virtual ObjectResult<sp_timesheet_report_Result> sp_timesheet_report(string startDate, string endDate, string status)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_timesheet_report_Result>("sp_timesheet_report", startDateParameter, endDateParameter, statusParameter);
        }
    
        public virtual ObjectResult<Sp_u_Result> Sp_u()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_u_Result>("Sp_u");
        }
    
        public virtual int Tasks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Tasks");
        }
    
        public virtual ObjectResult<userlist_Result> userlist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<userlist_Result>("userlist");
        }
    
        public virtual ObjectResult<Users_Result> Users()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Users_Result>("Users");
        }
    
        public virtual ObjectResult<string> Users22()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Users22");
        }
    
        public virtual ObjectResult<string> Users23()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Users23");
        }
    
        public virtual ObjectResult<string> Users30()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Users30");
        }
    
        public virtual ObjectResult<Users31_Result> Users31(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Users31_Result>("Users31", userParameter);
        }
    }
}
