//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_configs
    {
        public int Id { get; set; }
        public string APIkey { get; set; }
        public string partnerID { get; set; }
        public string shortcode { get; set; }
        public string APIUrl { get; set; }
    }
}
