//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sp_Charles_M : DbContext
    {
        public sp_Charles_M()
            : base("name=sp_Charles_M")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Acc_Profile_Result> Acc_Profile(string u)
        {
            var uParameter = u != null ?
                new ObjectParameter("u", u) :
                new ObjectParameter("u", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Acc_Profile_Result>("Acc_Profile", uParameter);
        }
    
        public virtual ObjectResult<AccessRolesSp_Result> AccessRolesSp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AccessRolesSp_Result>("AccessRolesSp");
        }
    
        public virtual int AddPhone(string phone, string email, string user)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddPhone", phoneParameter, emailParameter, userParameter);
        }
    
        public virtual int Checkin_Checkout(string username, string type)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Checkin_Checkout", usernameParameter, typeParameter);
        }
    
        public virtual int Delete_File(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_File", idParameter);
        }
    
        public virtual int Delete_User(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_User", usernameParameter);
        }
    
        public virtual ObjectResult<string> GetData(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetData", idParameter);
        }
    
        public virtual int GetEmp(string staffing)
        {
            var staffingParameter = staffing != null ?
                new ObjectParameter("Staffing", staffing) :
                new ObjectParameter("Staffing", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetEmp", staffingParameter);
        }
    
        public virtual ObjectResult<GetEmpUsername_Result> GetEmpUsername(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmpUsername_Result>("GetEmpUsername", idParameter);
        }
    
        public virtual int Getmail_TT(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Getmail_TT", idParameter);
        }
    
        public virtual ObjectResult<PushEmp_Result> PushEmp(string username, string email, string role)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PushEmp_Result>("PushEmp", usernameParameter, emailParameter, roleParameter);
        }
    
        public virtual int Role_Set(Nullable<int> id, string status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Role_Set", idParameter, statusParameter);
        }
    
        public virtual int SetRole(string status, string id, string role)
        {
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SetRole", statusParameter, idParameter, roleParameter);
        }
    
        public virtual ObjectResult<sp_add_item_Result> sp_add_item(string item)
        {
            var itemParameter = item != null ?
                new ObjectParameter("item", item) :
                new ObjectParameter("item", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_add_item_Result>("sp_add_item", itemParameter);
        }
    
        public virtual ObjectResult<sp_dash_Result> sp_dash(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dash_Result>("sp_dash", userParameter);
        }
    
        public virtual ObjectResult<sp_dash_2_Result> sp_dash_2(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dash_2_Result>("sp_dash_2", userParameter);
        }
    
        public virtual ObjectResult<sp_dash_3_Result> sp_dash_3(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dash_3_Result>("sp_dash_3", userParameter);
        }
    
        public virtual ObjectResult<sp_dash_4_Result> sp_dash_4(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dash_4_Result>("sp_dash_4", userParameter);
        }
    
        public virtual ObjectResult<sp_dash_Income_Result> sp_dash_Income(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dash_Income_Result>("sp_dash_Income", userParameter);
        }
    
        public virtual ObjectResult<string> sp_departments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_departments");
        }
    
        public virtual int sp_drop_expense(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_drop_expense", idParameter);
        }
    
        public virtual int sp_drop_Income(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_drop_Income", idParameter);
        }
    
        public virtual ObjectResult<sp_expenses_Result> sp_expenses()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_expenses_Result>("sp_expenses");
        }
    
        public virtual ObjectResult<sp_GetRoles_Result> sp_GetRoles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRoles_Result>("sp_GetRoles");
        }
    
        public virtual ObjectResult<sp_monthly_statement_Result> sp_monthly_statement(string user, string month_Name)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var month_NameParameter = month_Name != null ?
                new ObjectParameter("Month_Name", month_Name) :
                new ObjectParameter("Month_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_monthly_statement_Result>("sp_monthly_statement", userParameter, month_NameParameter);
        }
    
        public virtual ObjectResult<sp_months_list_Result> sp_months_list(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_months_list_Result>("sp_months_list", userParameter);
        }
    
        public virtual ObjectResult<sp_statement_footer_Result> sp_statement_footer(string user, string month_Name)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var month_NameParameter = month_Name != null ?
                new ObjectParameter("Month_Name", month_Name) :
                new ObjectParameter("Month_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_statement_footer_Result>("sp_statement_footer", userParameter, month_NameParameter);
        }
    
        public virtual ObjectResult<sp_Statements_Result> sp_Statements(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Statements_Result>("sp_Statements", usernameParameter);
        }
    }
}
