//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sp_Income_proc : DbContext
    {
        public sp_Income_proc()
            : base("name=sp_Income_proc")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_monthly_statement_Inc_Result> sp_monthly_statement_Inc(string user, string month_Name)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var month_NameParameter = month_Name != null ?
                new ObjectParameter("Month_Name", month_Name) :
                new ObjectParameter("Month_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_monthly_statement_Inc_Result>("sp_monthly_statement_Inc", userParameter, month_NameParameter);
        }
    
        public virtual ObjectResult<sp_Statements_Inc_Result> sp_Statements_Inc(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Statements_Inc_Result>("sp_Statements_Inc", usernameParameter);
        }
    }
}
