//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class tike_print : DbContext
    {
        public tike_print()
            : base("name=tike_print")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_print_grp_Result> sp_print_grp(string grpid)
        {
            var grpidParameter = grpid != null ?
                new ObjectParameter("Grpid", grpid) :
                new ObjectParameter("Grpid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_print_grp_Result>("sp_print_grp", grpidParameter);
        }
    
        public virtual ObjectResult<sp_print_grp_InvTT_Result> sp_print_grp_InvTT(string grpid)
        {
            var grpidParameter = grpid != null ?
                new ObjectParameter("Grpid", grpid) :
                new ObjectParameter("Grpid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_print_grp_InvTT_Result>("sp_print_grp_InvTT", grpidParameter);
        }
    }
}
