//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ZO : DbContext
    {
        public ZO()
            : base("name=ZO")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Acc_Profile_Result> Acc_Profile(string u)
        {
            var uParameter = u != null ?
                new ObjectParameter("u", u) :
                new ObjectParameter("u", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Acc_Profile_Result>("Acc_Profile", uParameter);
        }
    
        public virtual ObjectResult<AccessRolesSp_Result> AccessRolesSp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AccessRolesSp_Result>("AccessRolesSp");
        }
    
        public virtual int AddPhone(string phone, string email, string user)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddPhone", phoneParameter, emailParameter, userParameter);
        }
    
        public virtual ObjectResult<Approved_Employees_Result> Approved_Employees()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Approved_Employees_Result>("Approved_Employees");
        }
    
        public virtual int Auto_Assign_Staffing(string user, string employee)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var employeeParameter = employee != null ?
                new ObjectParameter("Employee", employee) :
                new ObjectParameter("Employee", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Auto_Assign_Staffing", userParameter, employeeParameter);
        }
    
        public virtual int Cancel_Shift(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cancel_Shift", idParameter);
        }
    
        public virtual ObjectResult<Check_F_Result> Check_F(string u)
        {
            var uParameter = u != null ?
                new ObjectParameter("u", u) :
                new ObjectParameter("u", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Check_F_Result>("Check_F", uParameter);
        }
    
        public virtual ObjectResult<Check_Pending_A_Result> Check_Pending_A(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Check_Pending_A_Result>("Check_Pending_A", userParameter);
        }
    
        public virtual int CheckStock(string product_Name, Nullable<int> sold_Quantity, Nullable<int> returnVal)
        {
            var product_NameParameter = product_Name != null ?
                new ObjectParameter("Product_Name", product_Name) :
                new ObjectParameter("Product_Name", typeof(string));
    
            var sold_QuantityParameter = sold_Quantity.HasValue ?
                new ObjectParameter("Sold_Quantity", sold_Quantity) :
                new ObjectParameter("Sold_Quantity", typeof(int));
    
            var returnValParameter = returnVal.HasValue ?
                new ObjectParameter("ReturnVal", returnVal) :
                new ObjectParameter("ReturnVal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CheckStock", product_NameParameter, sold_QuantityParameter, returnValParameter);
        }
    
        public virtual ObjectResult<Dash1_Result> Dash1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Dash1_Result>("Dash1");
        }
    
        public virtual int Delete_User(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_User", usernameParameter);
        }
    
        public virtual ObjectResult<string> DropDown()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DropDown");
        }
    
        public virtual ObjectResult<string> DropDown_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DropDown_All");
        }
    
        public virtual ObjectResult<string> DropDown_Cert()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DropDown_Cert");
        }
    
        public virtual ObjectResult<Em_Agency_Result> Em_Agency(string employee)
        {
            var employeeParameter = employee != null ?
                new ObjectParameter("employee", employee) :
                new ObjectParameter("employee", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Em_Agency_Result>("Em_Agency", employeeParameter);
        }
    
        public virtual ObjectResult<Em_Agency2_Result> Em_Agency2(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Em_Agency2_Result>("Em_Agency2", userParameter);
        }
    
       
    
        public virtual ObjectResult<string> Get_Clients()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Get_Clients");
        }
    
        public virtual ObjectResult<Get_Facilites_Result> Get_Facilites(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Facilites_Result>("Get_Facilites", userParameter);
        }
    
        public virtual ObjectResult<Get_FacilitesAdmin_Result> Get_FacilitesAdmin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_FacilitesAdmin_Result>("Get_FacilitesAdmin");
        }
    
        public virtual ObjectResult<GetEmp_Result> GetEmp(string staffing)
        {
            var staffingParameter = staffing != null ?
                new ObjectParameter("Staffing", staffing) :
                new ObjectParameter("Staffing", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmp_Result>("GetEmp", staffingParameter);
        }
    
        public virtual ObjectResult<GetEmpUsername_Result> GetEmpUsername(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmpUsername_Result>("GetEmpUsername", idParameter);
        }
    
        public virtual ObjectResult<GetFacility_Result> GetFacility()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFacility_Result>("GetFacility");
        }
    
        public virtual ObjectResult<GetFacilty_Acc_Result> GetFacilty_Acc(string staffing)
        {
            var staffingParameter = staffing != null ?
                new ObjectParameter("Staffing", staffing) :
                new ObjectParameter("Staffing", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFacilty_Acc_Result>("GetFacilty_Acc", staffingParameter);
        }
    
        public virtual ObjectResult<GetSetFacility_Result> GetSetFacility(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSetFacility_Result>("GetSetFacility", idParameter);
        }
    
        public virtual ObjectResult<GetShifts_Result> GetShifts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetShifts_Result>("GetShifts");
        }
    
        public virtual ObjectResult<GetStaffing_Acc_Result> GetStaffing_Acc(string staffing)
        {
            var staffingParameter = staffing != null ?
                new ObjectParameter("Staffing", staffing) :
                new ObjectParameter("Staffing", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStaffing_Acc_Result>("GetStaffing_Acc", staffingParameter);
        }
    
        public virtual int Onbehalf_Facility(string user, Nullable<int> id)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Onbehalf_Facility", userParameter, idParameter);
        }
    
        public virtual ObjectResult<PushEmp_Result> PushEmp(string username, string email, string role)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PushEmp_Result>("PushEmp", usernameParameter, emailParameter, roleParameter);
        }
    
        public virtual ObjectResult<RoleGrant_Result> RoleGrant()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RoleGrant_Result>("RoleGrant");
        }
    
        public virtual int RolesAdd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RolesAdd");
        }
    
        public virtual ObjectResult<rolesL_Result> rolesL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rolesL_Result>("rolesL");
        }
    
        public virtual int SetRole(string username, string role)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SetRole", usernameParameter, roleParameter);
        }
    
        public virtual ObjectResult<Shift_List_Result> Shift_List(string status, string certification, string employee)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var certificationParameter = certification != null ?
                new ObjectParameter("Certification", certification) :
                new ObjectParameter("Certification", typeof(string));
    
            var employeeParameter = employee != null ?
                new ObjectParameter("Employee", employee) :
                new ObjectParameter("Employee", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Shift_List_Result>("Shift_List", statusParameter, certificationParameter, employeeParameter);
        }
    
        public virtual ObjectResult<Shifts_Per_Agency_Result> Shifts_Per_Agency()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Shifts_Per_Agency_Result>("Shifts_Per_Agency");
        }
    
        public virtual ObjectResult<Shifts_Status_Result> Shifts_Status()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Shifts_Status_Result>("Shifts_Status");
        }
    
        public virtual ObjectResult<Sp_Agency_Profile_Result> Sp_Agency_Profile(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Agency_Profile_Result>("Sp_Agency_Profile", userParameter);
        }
    
        public virtual ObjectResult<Sp_Agency_Users_Result> Sp_Agency_Users()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Agency_Users_Result>("Sp_Agency_Users");
        }
    
        public virtual ObjectResult<Sp_Employee_Result> Sp_Employee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Employee_Result>("Sp_Employee");
        }
    
        public virtual ObjectResult<Sp_Employee_Per_A_Result> Sp_Employee_Per_A(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Employee_Per_A_Result>("Sp_Employee_Per_A", userParameter);
        }
    
        public virtual ObjectResult<Sp_Facility_Users_Result> Sp_Facility_Users()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Facility_Users_Result>("Sp_Facility_Users");
        }
    
        public virtual ObjectResult<Sp_u_Result> Sp_u()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_u_Result>("Sp_u");
        }
    
        public virtual ObjectResult<Tasks_Result> Tasks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tasks_Result>("Tasks");
        }
    
        public virtual ObjectResult<Tie_Result> Tie()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tie_Result>("Tie");
        }
    
        public virtual int TiedUpUsers(string facility, string user)
        {
            var facilityParameter = facility != null ?
                new ObjectParameter("Facility", facility) :
                new ObjectParameter("Facility", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TiedUpUsers", facilityParameter, userParameter);
        }
    
        public virtual ObjectResult<userlist_Result> userlist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<userlist_Result>("userlist");
        }
    
        public virtual ObjectResult<Users_Result> Users()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Users_Result>("Users");
        }
    
        public virtual ObjectResult<string> Users22()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Users22");
        }
    
        public virtual ObjectResult<string> Users23()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Users23");
        }
    
        public virtual ObjectResult<string> Users30()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Users30");
        }
    
        public virtual ObjectResult<Users31_Result> Users31(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Users31_Result>("Users31", userParameter);
        }
    }
}
